export const occupationOptions = [
  { value: "", label: "Pilih Pekerjaan", code: "" },
  { value: "buruh", label: "Buruh", code: "93" },
  { value: "guru", label: "Guru/Dosen", code: "23" },
  { value: "ibu_rumah_tangga", label: "Ibu Rumah Tangga", code: "96" },
  { value: "mahasiswa", label: "Mahasiswa", code: "25" },
  { value: "nelayan", label: "Nelayan", code: "62" },
  { value: "pegawai_negeri", label: "Pegawai Negeri Sipil", code: "45" },
  { value: "pegawai_swasta", label: "Pegawai Swasta", code: "99" },
  { value: "pekerja_harian", label: "Pekerja Harian Lepas", code: "94" },
  { value: "pengusaha", label: "Pengusaha", code: "13" },
  { value: "pensiunan", label: "Pensiunan", code: "81" },
  { value: "petani", label: "Petani", code: "61" },
  { value: "polri", label: "Polri", code: "33" },
  { value: "praktisi_hukum", label: "Praktisi Hukum", code: "69" },
  { value: "supir", label: "Supir", code: "83" },
  { value: "tni", label: "TNI", code: "86" },
  { value: "tenaga_kesehatan", label: "Tenaga Kesehatan", code: "11" },
  { value: "wirausaha", label: "Wirausaha", code: "47" },
  { value: "wiraswasta", label: "Wiraswasta", code: "95" },
  { value: "lainnya", label: "Lainnya", code: "55" },
];
