export const occupationOptions = [
  { value: '', label: 'Pilih Pekerjaan', code: '' },
  { value: 'pegawai_negeri', label: 'Pegawai Negeri Sipil', code: '001' },
  { value: 'pegawai_swasta', label: 'Pegawai Swasta', code: '002' },
  { value: 'wiraswasta', label: 'Wiraswasta', code: '003' },
  { value: 'pengusaha', label: 'Pengusaha', code: '004' },
  { value: 'petani', label: 'Petani', code: '005' },
  { value: 'nelayan', label: 'Nelayan', code: '006' },
  { value: 'guru', label: 'Guru/Dosen', code: '007' },
  { value: 'dokter', label: 'Dokter', code: '008' },
  { value: 'bidan', label: 'Bidan', code: '009' },
  { value: 'perawat', label: 'Perawat', code: '010' },
  { value: 'polri', label: 'Polri', code: '011' },
  { value: 'tni', label: 'TNI', code: '012' },
  { value: 'pensiunan', label: 'Pensiunan', code: '013' },
  { value: 'mahasiswa', label: 'Mahasiswa', code: '014' },
  { value: 'ibu_rumah_tangga', label: 'Ibu Rumah Tangga', code: '015' },
  { value: 'buruh', label: 'Buruh', code: '016' },
  { value: 'supir', label: 'Supir', code: '017' },
  { value: 'tukang', label: 'Tukang', code: '018' },
  { value: 'pedagang', label: 'Pedagang', code: '019' },
  { value: 'lainnya', label: 'Lainnya', code: '999' },
];