  // Options for select fields
  export const provinceOptions = [
    { value: '', label: 'Pilih Provinsi' },
    { value: 'aceh', label: 'Aceh' },
    { value: 'sumut', label: 'Sumatera Utara' },
    { value: 'sumbar', label: 'Sumatera Barat' },
    { value: 'riau', label: 'Riau' },
    { value: 'jambi', label: 'Jambi' },
    { value: 'sumsel', label: 'Sumatera Selatan' },
    { value: 'bengkulu', label: 'Bengkulu' },
    { value: 'lampung', label: 'Lampung' },
    { value: 'babel', label: 'Bangka Belitung' },
    { value: 'kepri', label: 'Kepulauan Riau' },
    { value: 'jakarta', label: 'DKI Jakarta' },
    { value: 'jabar', label: 'Jawa Barat' },
    { value: 'jateng', label: 'Jawa Tengah' },
    { value: 'yogya', label: 'D.I. Yogyakarta' },
    { value: 'jatim', label: 'Jawa Timur' },
    { value: 'banten', label: 'Banten' },
    { value: 'bali', label: 'Bali' },
    { value: 'ntb', label: 'Nusa Tenggara Barat' },
    { value: 'ntt', label: 'Nusa Tenggara Timur' },
    { value: 'kalbar', label: 'Kalimantan Barat' },
    { value: 'kalteng', label: 'Kalimantan Tengah' },
    { value: 'kalsel', label: 'Kalimantan Selatan' },
    { value: 'kaltim', label: 'Kalimantan Timur' },
    { value: 'kaltara', label: 'Kalimantan Utara' },
    { value: 'sulut', label: 'Sulawesi Utara' },
    { value: 'sulteng', label: 'Sulawesi Tengah' },
    { value: 'sulsel', label: 'Sulawesi Selatan' },
    { value: 'sultra', label: 'Sulawesi Tenggara' },
    { value: 'gorontalo', label: 'Gorontalo' },
    { value: 'sulbar', label: 'Sulawesi Barat' },
    { value: 'maluku', label: 'Maluku' },
    { value: 'malut', label: 'Maluku Utara' },
    { value: 'papua', label: 'Papua' },
    { value: 'papbar', label: 'Papua Barat' },
  ];
